# Generated by Django 5.0.4 on 2024-05-02 10:13

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubadmins', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', events.models.CustomEventID(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=500)),
                ('min_team_size', models.IntegerField()),
                ('max_team_size', models.IntegerField()),
                ('registration_fee', models.IntegerField()),
                ('prize_money', models.IntegerField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubadmins.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', events.models.CustomRegID(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('team_size', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader_name', models.CharField(max_length=100)),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(max_length=100)),
                ('member_3', models.CharField(max_length=100)),
                ('member_4', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('member_1_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_1_registration', to='users.students')),
                ('member_2_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_2_registration', to='users.students')),
                ('member_3_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_3_registration', to='users.students')),
                ('member_4_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_4_registration', to='users.students')),
                ('team_leader_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_registration', to='users.students')),
            ],
        ),
    ]
