# Generated by Django 5.0.4 on 2024-05-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options_events_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='team_leader_name',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='team_leader_rollno',
        ),
    ]
