# Generated by Django 5.0.4 on 2024-05-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_registrations_team_leader_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='member_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_2_rollno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_2_registration', to='users.students'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_3_rollno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_3_registration', to='users.students'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='member_4_rollno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_4_registration', to='users.students'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='team_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
