# Generated by Django 5.0.4 on 2024-05-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'ordering': ('name',)},
        ),
    ]
