# Generated by Django 5.0.4 on 2024-06-07 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmins', '0002_alter_clubs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
